server:
  port: 9012
eureka:
  server:
#    enable-self-preservation: false
    eviction-interval-timer-in-ms: 200000
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://10.211.55.8:30060/eureka/
spring:
  application:
    name: eureka-server
  mail:
    default-encoding: utf-8
    host: smtp.qq.com
    username: 1511836114@qq.com
    password: gpanozdmuvaxfgbf
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mail:
  from: ${spring.mail.username}
  to: xuanmine@gmail.com
