server:
  port: 9100
eureka:
  server:
#    enable-self-preservation: false
    eviction-interval-timer-in-ms: 200000
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9100/eureka/
spring:
  application:
    name: eureka-server