server:
  port: 9100
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: ~/IdeaProjects/fluxdemo/config-yml
        bootstrap: true
management:
  security:
    enabled: false
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:9100/eureka/